version: '3.7'

services:
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3000:3000
  api:
    build: ./server
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acamicaportal
      MYSQL_USER: sa
      MYSQL_PASSWORD: PASSWORD
    volumes:
      - ../../db/mysql:/var/lib/mysql

volumes:
  mysql: